[package]
name = "injeqtor"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.7", features = ["json"] }
tokio = { version = "1.40.0", features = ["full"] }
scraper = "0.20.0"
regex = "1.11.0"
colored = "2"
clap = "4.5.18"