[package]
name = "injectsql"
version = "0.1.0"
edition = "2021"
authors = ["João Lucas <joaolucasfp2001@gmail.com>"]
license = "MIT"
description = "Command Line Tools to check for SQL Injection vulnerability."
readme = "README.md"
repository = "https://github.com/heroesofcode/inject-sql"
exclude = [".github/**"]

[dependencies]
reqwest = { version = "0.12.8", features = ["json"] }
tokio = { version = "1.40.0", features = ["full"] }
scraper = "0.20.0"
regex = "1.11.0"
colored = "2.1.0"
clap = "4.5.20"