[package]
name = "injeqtor"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.4", features = ["json"] }
tokio = { version = "1.38.0", features = ["full"] }
scraper = "0.19.0"
regex = "1.10.4"
colored = "2"
clap = "4.5.7"