# macOS (x86_64 and aarch64)
[target.x86_64-apple-darwin]
linker = "clang"

[target.aarch64-apple-darwin]
linker = "clang"

# Linux (x86_64 and aarch64)
[target.x86_64-unknown-linux-gnu]
linker = "gcc"

[target.aarch64-unknown-linux-gnu]
linker = "gcc"

# Windows (MSVC)
[target.x86_64-pc-windows-msvc]
linker = "clang-cl"

[target.aarch64-pc-windows-msvc]
linker = "clang-cl"

# Windows (GNU)
[target.x86_64-pc-windows-gnu]
linker = "gcc"

[target.aarch64-pc-windows-gnu]
linker = "gcc"